Repository saagie/sdk, pull requests merged in 2020-07, with the labels that each got.

#85 ✨ implement text area type field
  .github/workflows/pull_request.yml
  packages/webapp/.eslintrc.js
  packages/webapp/src/components/SmartField.js
  packages/webapp/src/contexts/YAMLConfigContext.js
Labels: minor

#86 ✨ Implement Radio type field
  packages/webapp/src/components/SmartField.js
Labels: minor, release

#89 🐛 logs component is more stable
  packages/webapp/src/components/Logs/Line.js
  packages/webapp/src/components/Logs/Logs.js
  packages/webapp/src/contexts/LogsContext.js
  packages/webapp/src/hooks/useWindowSize.js
Labels: bug, patch, release

#91 fix: release all packages on update
  package.json
Labels: bug, patch, release

#92 fix: remove the * --force-publish don't need it
  package.json
Labels: bug, patch, release
